### ISSUE TITLE
renter.HostKeyResolver

### ISSUE THREAD

**Issue by jkawamoto** [lukechampine/walrus#13]
Would it be possible that `walrus.Client` implements `renter.HostKeyResolver` interface?

I think the host DB is provided by https://github.com/lukechampine/shard, and we need to run both walrus and shard. However, both of them need to have a copy of the consensus DB, and running two servers seems not efficient storage-wise and network traffic-wise.

It would be nice if walrus can provide host DB or walrus and shard servers can share one copy of the consensus DB.

**Comment by lukechampine** [comment]
Recently I added support to `muse` for running both a `walrus` instance and `shard` instance from the same consensus set: https://github.com/lukechampine/muse/commit/0906d74036b2b8a12c717d2abdc641a541bc4c8e

I would also like to add support for HTTP consensus subscription to `walrus` and `shard` so that you can use them with an existing `siad` node. That will be slightly less stable and performant, though, so I recommend using `muse`.
