### ISSUE TITLE
Get limbo API doesn't return transaction IDs and limboSince

### ISSUE THREAD

**Issue by jkawamoto** [lukechampine/walrus#18]
Looks like Get limbo API doesn't return transaction IDs and limboSince with v0.10.5. 

```
root@muse-0:~# curl -s http://localhost:9380/limbo | jq ".[].id"
null
null
null
null
null
null
null

root@muse-0:~# curl -s http://localhost:9380/limbo | jq ".[].limboSince"
null
null
null
null
null
null
null
```

**Comment by jkawamoto** [comment]
Commenting out `JSONTransaction.MarshalJSON` fixes this problem. Not sure if it drops other attributes, though.

**Comment by lukechampine** [comment]
Oof, apologies for the breakage. This happened because the `LimboTransaction` encoder embeds a `JSONTransaction` field, causing the whole struct to inherit its `MarshalJSON` method. Fixed in https://github.com/lukechampine/walrus/commit/09ddf19c93b4109f0518db308265329f78c3ede4 (and tagged as v0.10.6)

**Comment by jkawamoto** [comment]
Thanks for fixing this issue quickly!
